
	printf("%d\n",printf("%#d\n", 42));
	printf("%d\n",printf("%#d\n", 0));
	printf("%d\n",printf("%#d\n", -42));
	printf("%d\n",printf("%###############d\n", 42));
	printf("%d\n",printf("%###############d\n", 0));
	printf("%d\n",printf("%###############d\n", -42));
	printf("%d\n",printf("%########++++++++d\n", 42));
	printf("%d\n",printf("%########++++++++d\n", 0));
	printf("%d\n",printf("%########++++++++d\n", -42));
	printf("%d\n",printf("%++++++++########d\n", 42));
	printf("%d\n",printf("%++++++++########d\n", 0));
	printf("%d\n",printf("%++++++++########d\n", -42));
	printf("%d\n",printf("%########--------d\n", 42));
	printf("%d\n",printf("%########--------d\n", 0));
	printf("%d\n",printf("%########--------d\n", -42));
	printf("%d\n",printf("%--------########d\n", 42));
	printf("%d\n",printf("%--------########d\n", 0));
	printf("%d\n",printf("%--------########d\n", -42));
	printf("%d\n",printf("%########00000000d\n", 42));
	printf("%d\n",printf("%########00000000d\n", 0));
	printf("%d\n",printf("%########00000000d\n", -42));
	printf("%d\n",printf("%00000000########d\n", 42));
	printf("%d\n",printf("%00000000########d\n", 0));
	printf("%d\n",printf("%00000000########d\n", -42));
	printf("%d\n",printf("%########        d\n", 42));
	printf("%d\n",printf("%########        d\n", 0));
	printf("%d\n",printf("%########        d\n", -42));
	printf("%d\n",printf("%        ########d\n", 42));
	printf("%d\n",printf("%        ########d\n", 0));
	printf("%d\n",printf("%        ########d\n", -42));
	printf("%d\n",printf("%++++++++########d\n", 42));
	printf("%d\n",printf("%++++++++########d\n", 0));
	printf("%d\n",printf("%++++++++########d\n", -42));
	printf("%d\n",printf("%########++++++++d\n", 42));
	printf("%d\n",printf("%########++++++++d\n", 0));
	printf("%d\n",printf("%########++++++++d\n", -42));
	printf("%d\n",printf("%++++++++00000000d\n", 42));
	printf("%d\n",printf("%++++++++00000000d\n", 0));
	printf("%d\n",printf("%++++++++00000000d\n", -42));
	printf("%d\n",printf("%-+#0 d\n", 42));
	printf("%d\n",printf("%-+#0 d\n", 0));
	printf("%d\n",printf("%-+#0 d\n", -42));
	printf("%d\n",printf("%-+# 0d\n", 42));
	printf("%d\n",printf("%-+# 0d\n", 0));
	printf("%d\n",printf("%-+# 0d\n", -42));
	printf("%d\n",printf("%-+0 #d\n", 42));
	printf("%d\n",printf("%-+0 #d\n", 0));
	printf("%d\n",printf("%-+0 #d\n", -42));
	printf("%d\n",printf("%-+0# d\n", 42));
	printf("%d\n",printf("%-+0# d\n", 0));
	printf("%d\n",printf("%-+0# d\n", -42));
	printf("%d\n",printf("%+-#0 d\n", 42));
	printf("%d\n",printf("%+-#0 d\n", 0));
	printf("%d\n",printf("%+-#0 d\n", -42));
	printf("%d\n",printf("%+- #0d\n", 42));
	printf("%d\n",printf("%+- #0d\n", 0));
	printf("%d\n",printf("%+- #0d\n", -42));
	printf("%d\n",printf("%+- 0#d\n", 42));
	printf("%d\n",printf("%+- 0#d\n", 0));
	printf("%d\n",printf("%+- 0#d\n", -42));
	printf("%d\n",printf("%+ -#0d\n", 42));
	printf("%d\n",printf("%+ -#0d\n", 0));
	printf("%d\n",printf("%+ -#0d\n", -42));
	printf("%d\n",printf("%+ -0#d\n", 42));
	printf("%d\n",printf("%+ -0#d\n", 0));
	printf("%d\n",printf("%+ -0#d\n", -42));
	printf("%d\n",printf("% +-#0d\n", 42));
	printf("%d\n",printf("% +-#0d\n", 0));
	printf("%d\n",printf("% +-#0d\n", -42));
	printf("%d\n",printf("% +-0#d\n", 42));
	printf("%d\n",printf("% +-0#d\n", 0));
	printf("%d\n",printf("% +-0#d\n", -42));
	printf("%d\n",printf("% -+#0d\n", 42));
	printf("%d\n",printf("% -+#0d\n", 0));
	printf("%d\n",printf("% -+#0d\n", -42));
	printf("%d\n",printf("% -+0#d\n", 42));
	printf("%d\n",printf("% -+0#d\n", 0));
	printf("%d\n",printf("% -+0#d\n", -42));
	printf("%d\n",printf("%- +#0d\n", 42));
	printf("%d\n",printf("%- +#0d\n", 0));
	printf("%d\n",printf("%- +#0d\n", -42));
	printf("%d\n",printf("%- +0#d\n", 42));
	printf("%d\n",printf("%- +0#d\n", 0));
	printf("%d\n",printf("%- +0#d\n", -42));
	printf("%d\n",printf("%- #+0d\n", 42));
	printf("%d\n",printf("%- #+0d\n", 0));
	printf("%d\n",printf("%- #+0d\n", -42));
	printf("%d\n",printf("%- 0+#d\n", 42));
	printf("%d\n",printf("%- 0+#d\n", 0));
	printf("%d\n",printf("%- 0+#d\n", -42));
	printf("%d\n",printf("%- #0+d\n", 42));
	printf("%d\n",printf("%- #0+d\n", 0));
	printf("%d\n",printf("%- #0+d\n", -42));
	printf("%d\n",printf("%- 0#+d\n", 42));
	printf("%d\n",printf("%- 0#+d\n", 0));
	printf("%d\n",printf("%- 0#+d\n", -42));
	printf("%d\n",printf("% -+#0d\n", 42));
	printf("%d\n",printf("% -+#0d\n", 0));
	printf("%d\n",printf("% -+#0d\n", -42));
	printf("%d\n",printf("% -+0#d\n", 42));
	printf("%d\n",printf("% -+0#d\n", 0));
	printf("%d\n",printf("% -+0#d\n", -42));
	printf("%d\n",printf("% -#+0d\n", 42));
	printf("%d\n",printf("% -#+0d\n", 0));
	printf("%d\n",printf("% -#+0d\n", -42));
	printf("%d\n",printf("% -0+#d\n", 42));
	printf("%d\n",printf("% -0+#d\n", 0));
	printf("%d\n",printf("% -0+#d\n", -42));
	printf("%d\n",printf("% -#0+d\n", 42));
	printf("%d\n",printf("% -#0+d\n", 0));
	printf("%d\n",printf("% -#0+d\n", -42));
	printf("%d\n",printf("% -0#+d\n", 42));
	printf("%d\n",printf("% -0#+d\n", 0));
	printf("%d\n",printf("% -0#+d\n", -42));
	printf("%d\n",printf("% +#-0d\n", 42));
	printf("%d\n",printf("% +#-0d\n", 0));
	printf("%d\n",printf("% +#-0d\n", -42));
	printf("%d\n",printf("% +0-#d\n", 42));
	printf("%d\n",printf("% +0-#d\n", 0));
	printf("%d\n",printf("% +0-#d\n", -42));
	printf("%d\n",printf("% -#+0d\n", 42));
	printf("%d\n",printf("% -#+0d\n", 0));
	printf("%d\n",printf("% -#+0d\n", -42));
	printf("%d\n",printf("% -0+#d\n", 42));
	printf("%d\n",printf("% -0+#d\n", 0));
	printf("%d\n",printf("% -0+#d\n", -42));
	printf("%d\n",printf("% -#0+d\n", 42));
	printf("%d\n",printf("% -#0+d\n", 0));
	printf("%d\n",printf("% -#0+d\n", -42));
	printf("%d\n",printf("% -0#+d\n", 42));
	printf("%d\n",printf("% -0#+d\n", 0));
	printf("%d\n",printf("% -0#+d\n", -42));
	printf("%d\n",printf("%++++++++        d\n", 42));
	printf("%d\n",printf("%++++++++        d\n", 0));
	printf("%d\n",printf("%++++++++        d\n", -42));
	printf("%d\n",printf("%        ++++++++d\n", 42));
	printf("%d\n",printf("%        ++++++++d\n", 0));
	printf("%d\n",printf("%        ++++++++d\n", -42));
	printf("%d\n",printf("%--------00000000d\n", 42));
	printf("%d\n",printf("%--------00000000d\n", 0));
	printf("%d\n",printf("%--------00000000d\n", -42));
	printf("%d\n",printf("%00000000--------d\n", 42));
	printf("%d\n",printf("%00000000--------d\n", 0));
	printf("%d\n",printf("%00000000--------d\n", -42));
// ----------- invalid printf ---------

	printf("------- invalid --------\n");
	printf("%d\n", printf("aha!\n", 42));
	printf("%d\n", printf("%d\n"));
	printf("%d\n", printf("%h\n"));
	printf("%d\n", printf("%yd\n", 42));
	printf("%d\n", printf("%ll3.5\n", 42));
	printf("%d\n", printf("%ld%hd%d\n", (short)42, (long)0, -42));
	printf("%d\n", printf("%ld%hd%d\n", (short)42, 0, (long)-42));
	printf("%d\n",printf("%--------00000000o\n", 42));
	printf("%d\n",printf("%--------00000000o\n", 0));
	printf("%d\n",printf("%--------00000000o\n", -42));
	printf("%d\n",printf("%00000000--------o\n", 42));
	printf("%d\n",printf("%00000000--------o\n", 0));
	printf("%d\n",printf("%00000000--------o\n", -42));
	printf("%d\n",printf("%--------00000000x\n", 42));
	printf("%d\n",printf("%--------00000000x\n", 0));
	printf("%d\n",printf("%--------00000000x\n", -42));
	printf("%d\n",printf("%00000000--------x\n", 42));
	printf("%d\n",printf("%00000000--------x\n", 0));
	printf("%d\n",printf("%00000000--------x\n", -42));
